name: Build Opacity Micro-Map SDK
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      -
        name : Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          
      - name: Setup CMake Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'
      -
        name: Install Windows SDK and CMake
        if: ${{ matrix.os == 'windows-latest' }}
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install windows-sdk-10.0 cmake -y
      -
        name: Install Vulkan
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
          echo Vulkan SDK version $ver
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
          echo Downloaded
          .\VulkanSDK.exe --root C:\VulkanSDK --accept-licenses --default-answer --confirm-command install
      -
        name: CMake Config Win
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          mkdir "build"
          cd "build"
          cmake .. -A x64
          cd ..
      -
        name: CMake Config Ubuntu
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          mkdir "build"
          cd "build"
          cmake .. -A x64
          cd ..
      -
        name: Build Debug
        run: |
          cd "build"
          cmake --build . --config Debug
          cd ..
      -
        name: Build Release
        run: |
          cd "build"
          cmake --build . --config Release
          cd ..
